FROM python:3.6-slim-stretch

RUN apt-get update
RUN apt-get install -y   build-essential
RUN apt-get install -y   cmake
# RUN apt-get install -y   pkg-config
RUN apt-get install -y   libpng-dev
RUN apt-get install -y   libxvidcore-dev
RUN apt-get install -y   libx264-dev
RUN apt-get install -y   libgtk-3-dev
RUN apt-get install -y   libcanberra-gtk3-module
RUN apt-get install -y   python3-dev
RUN apt-get install -y   git
RUN apt-get install -y python-tk

RUN pip install --user --upgrade pip
RUN pip install numpy
RUN pip install opencv-contrib-python
RUN pip install requests
RUN pip install simplejson

