apiVersion: apps/v1
kind: Deployment
metadata:
  name: recog-deployment
  labels:
    app: recog-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recog-image
  template:
    metadata:
      labels:
        app: recog-image
    spec:
      containers:
      - name: demo-recog
        image: demo-recog:1
        tty: true
        env:
        - name: DISPLAY
          value: unix0
        volumeMounts:
        - mountPath: /dev/video0
          name: video
        - mountPath: /home/face_recognition/data
          name: data
        - mountPath: /tmp/.X11-unix
          name: screen
        securityContext:
          privileged: true
        ports:
        - containerPort: 8000
          hostPort: 8000
      volumes:
      - name: video
        hostPath:
          path: /dev/video0
      - name: data
        hostPath:
          path: /home/root1/go/src/github.com/kubeedge/kubeedge/demo/data
      - name: screen
        hostPath:
          path: /tmp/.X11-unix
      hostNetwork: true
      nodeSelector:
        dedicated: edge

